// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7HuTN733WCDVDnqIcZoVa9dHoKxFQiGU',
    appId: '1:196957139092:android:3497686abd5c9ff7e4c481',
    messagingSenderId: '196957139092',
    projectId: 'concordia-academy-app',
    storageBucket: 'concordia-academy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3f9UDt3wmkiudOmzZXv3oaD5akBUz_w',
    appId: '1:196957139092:ios:c088ad7c03bd67bae4c481',
    messagingSenderId: '196957139092',
    projectId: 'concordia-academy-app',
    storageBucket: 'concordia-academy-app.firebasestorage.app',
    iosBundleId: 'com.example.concordiaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI3f9UDt3wmkiudOmzZXv3oaD5akBUz_w',
    appId: '1:196957139092:ios:c088ad7c03bd67bae4c481',
    messagingSenderId: '196957139092',
    projectId: 'concordia-academy-app',
    storageBucket: 'concordia-academy-app.firebasestorage.app',
    iosBundleId: 'com.example.concordiaAdmin',
  );
}
